from pydantic import BaseModel, Field
from typing import Dict, Any, Optional

class AgentRequest(BaseModel):
    """Schema for a request sent to an agent."""
    task_id: str = Field(..., description="Unique identifier for the task.")
    agent_id: str = Field(..., description="ID of the agent receiving the request.")
    instruction: str = Field(..., description="The task instruction to execute.")
    context: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Additional context or payload for the task.")

class AgentResponse(BaseModel):
    """Schema for a response generated by an agent."""
    task_id: str = Field(..., description="Unique identifier for the task.")
    status: str = Field(..., description="Status of the task (e.g., 'success', 'failure', 'pending').")
    result: Optional[Dict[str, Any]] = Field(None, description="The result payload of the task execution.")
    error_message: Optional[str] = Field(None, description="Error message if the task failed.")

class TaskDelegation(BaseModel):
    """Schema for delegating a task to another agent."""
    parent_task_id: str = Field(..., description="ID of the parent task delegating the work.")
    sub_task_id: str = Field(..., description="Unique identifier for the new sub-task.")
    target_agent_id: str = Field(..., description="ID of the agent to which the task is delegated.")
    instruction: str = Field(..., description="Instruction for the delegated task.")
